### ISSUE TITLE
NPM上面的版本不可用

### ISSUE THREAD

**Issue by kamikat** [small-tou/node-renren#2]
RT，NPM上的版本调用

var api = new Renren(cfg);
返回的是一个object……

也许是已过期，请更新

**Comment by small-tou** [comment]
更新了一下，不过new RenRen 的确返回的是一个object。详见 https://github.com/xinyu198736/node-renren/blob/master/README.md

**Comment by kamikat** [comment]
OwO 可是貌似github上clone下去的可以用……

如果可以的话请添加component.js以使仓库支持[component](https://github.com/component)和[bower](http://twitter.github.com/bower/)
